# Generated by Django 4.2.4 on 2023-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAL_INSIGHTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='balance',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='termination_code',
            field=models.CharField(max_length=100),
        ),
    ]
